server:
  port: 8761

eureka:
  instance:
    # Eureka Server 节点名
#    hostname: Eureka_Server
    prefer-ip-address: true
  client:
    # 表示是否将自己注册到Eureka Server，默认为true
    registerWithEureka: true
    # 表示是否从Eureka Server获取注册信息，默认为true
    fetchRegistry: true
    # 与Eureka Server交互的地址，默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/,http://peer2:8761/eureka/,http://peer3:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
